name: Publish Project Snapshot

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 3 * * 1,4'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Write Gradle build properties to `~/.gradle/gradle.properties`
        run: |
          mkdir -p ~/.gradle
          printf "org.gradle.jvmargs=-Xmx3G -XX:+UseParallelGC\n" >> ~/.gradle/gradle.properties
          printf "org.gradle.vfs.watch=false\n" >> ~/.gradle/gradle.properties
        shell: bash

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 24

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew assemble

      - name: Publish to Github Package Registry
        run: ./gradlew publishAllPublicationsToGithubRepository

  diffuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Write Gradle build properties to `~/.gradle/gradle.properties`
        run: |
          mkdir -p ~/.gradle
          printf "org.gradle.jvmargs=-Xmx3G -XX:+UseParallelGC\n" >> ~/.gradle/gradle.properties
          printf "org.gradle.vfs.watch=false\n" >> ~/.gradle/gradle.properties
        shell: bash

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 24

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew assemble -PskipJarVersion

      - name: Upload diffuse base artifact
        uses: actions/cache@v4
        with:
          path: diffuse-base-file
          key: diffuse-${{ github.sha }}

      - name: Check size
        run: du -h ktlint-gradle-plugin/build/libs/ktlint-gradle-plugin.jar
        shell: bash

      - name: Copy diffuse base artifact to be picked by cache save
        run: cp ktlint-gradle-plugin/build/libs/ktlint-gradle-plugin.jar diffuse-base-file
        shell: bash
